name: build
on:
  - push
env:
  COMPOSER_HOME: ~/.composer
  PHP_VERSION: 7.4
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Use PHP ${{ env.PHP_VERSION }}
        run: |
          sudo update-alternatives --set php /usr/bin/php${PHP_VERSION}
          sudo update-alternatives --set phar /usr/bin/phar${PHP_VERSION}
          sudo update-alternatives --set phpdbg /usr/bin/phpdbg${PHP_VERSION}
          sudo update-alternatives --set php-cgi /usr/bin/php-cgi${PHP_VERSION}
          sudo update-alternatives --set phar.phar /usr/bin/phar.phar${PHP_VERSION}
          php -version
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          path: ${{ env.COMPOSER_HOME }}
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer run lint
      - name: Test
        run: composer run test
