name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Lint
        run: composer run lint
      - name: Test
        run: composer run test
